### ISSUE TITLE
Sample code fails with Cosmos DB

### ISSUE THREAD

**Issue by neildonkin** [ExRam/ExRam.Gremlinq.Samples#10]
I have executed your sample code against a Cosmos DB consumption plan graph database.  All of the sample code works except for `Set_and_get_metadata_on_Marko`, which fails with this error message:

`Gremlin Query Execution Error: The graph collection is in the SimpleVertexProperty mode. The property Creator cannot be added/updated with meta properties.`

**Comment by danielcweber** [comment]
Unfortunately, I can't reproduce this error on my CosmosDB account, nor have I ever seen this error message.  Is there more info in the error message?

**Comment by neildonkin** [comment]
Thanks for the quick reply.

Sorry, there was no other information that I could see.

In that case I will close the issue.

**Comment by danielcweber** [comment]
You could always post a minimal working repro project over in the main project repo. Transferring the issue.
