### ISSUE TITLE
Add example for Repeat

### ISSUE THREAD

**Issue by jiatao99** [ExRam/ExRam.Gremlinq.Samples#14]
Can you please add example of how to use Repeat?

I tried the function below:

```
        [Fact]
        public async void MarkKnowsRepeat()
        {
            var g = base.Connect("Person");
            // connecting Josh to Peter
            await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Josh")
                .AddE<Knows>()
                .To(__ => __.V<Person>().Where(a => a.Name!.Value == "Peter"))
                .FirstAsync();

            var knownPersonsToMarko = await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Marko")
                .Out<Knows>()
                .OfType<Person>()
                .RepeatUntil(_ => _.Out<Knows>().OfType<Person>(), 
                            __ => __.V<Person>().Where(a => a.Name!.Value == "Marko"))
                .Values(x => x.Name!)
                .ToArrayAsync();

            await Output.WriteLineAsync($"Who does  know?");

            foreach (var person in knownPersonsToMarko)
            {
                await Output.WriteLineAsync($"Marko knows {person}.");
            }

            await Output.WriteLineAsync();
        }
```

Here is the output:

```
Who does  know?
Marko knows Marko.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
Marko knows Peter.
```

**Comment by danielcweber** [comment]
What are you trying to achieve? Yes, there should be an example for Repeat. Until then, check out the [Tinkerpop docs](https://tinkerpop.apache.org/docs/current/reference/#repeat-step) to learn about the semantics of Repeat-Until/Until-Repeat.

**Comment by danielcweber** [comment]
It seems odd that 'Marko knows Marko' should be an output of the above setup (unless you created a Knows-edge between Marko and himself). The line  `__ => __.V<Person>().Where(a => a.Name!.Value == "Marko")` is the break-condition of the repeat loop, which looks not like something you really want since it is either true all the time or false all the time - it doesn't depend on the current state of the repeat traversal. Not sure what your break condition was intended to be. If you want it to be true all the time, use `__ => __`. If your intention was to break infinite "knows" loops on Marko, omit the "V(...)".

**Comment by jiatao99** [comment]
What I am trying to do is see how to write repeat function using this awesome library. 

In this case, find all the social connection using "Knows" start with Marko. 

1. Since I have a knows edge from Vadas back to Marko (both Marko -> Vadas and Vadas -> Marko), the until condition is used to break the circular reference. (Otherwise I got exception)
2. Draw path is what I really interested in the GraphDB. Therefore, I think the repeat function is a key feature to use? For example, find all the path from a to b. 
3. Since API in this library is a little bit different than Gremlin, I suggest to add an example for repeat function.

Thanks

**Comment by danielcweber** [comment]
To really break the cycle, drop the mid-`V()`-step in `__ => __.V<Person>().Where(a => a.Name!.Value == "Marko")`. As it is, this is a global lookup and will always yield Marko!

**Comment by jiatao99** [comment]
Thanks for your quick reply.

As I said, if I remove the __ => __.V<person>, I got exception if there is a circular reference ( Vadas <-Knows-> Mark)

Anyway, I removed the back edge from Vadas -> Mark and use repeat function as below:

```
            var g = base.Connect("Person");
            // connecting Josh to Peter
            await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Josh")
                .AddE<Knows>()
                .To(__ => __.V<Person>().Where(a => a.Name!.Value == "Peter"))
                .FirstAsync();

            var knownPersonsToMarko = await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Marko")
                .Out<Knows>()
                .OfType<Person>()
                .Repeat(_ => _.Out<Knows>().OfType<Person>())
                .Values(x => x.Name!)
                .ToArrayAsync();

            await Output.WriteLineAsync($"Who does Marko know directly of indirectly?");

            foreach (var person in knownPersonsToMarko)
            {
                await Output.WriteLineAsync($"Marko knows {person}.");
            }

            await Output.WriteLineAsync();
```

The output
```
Who does Marko know directly of indirectly?
```

Confused on how to use repeat.

**Comment by danielcweber** [comment]
Would you know how to formulate your intention in raw Gremlin ?

**Comment by jiatao99** [comment]
Thanks. I am pretty new to Gremlin and tried to use your lib as self study guide. I finally make it work using

```
            var knownPersonsToMarko = await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Marko")
                .Repeat(_ => _.Out<Knows>().OfType<Person>())
                .Emit()
                .SimplePath()
                .Dedup()
                .ToArrayAsync();
```
 
However, whenever I have a circular reference, I got max loop encountered exception

```
        [Fact]
        public async void MarkKnowsRepeat()
        {
            var g = base.Connect("Person");
            // connecting Josh to Peter
            await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Josh")
                .AddE<Knows>()
                .To(__ => __.V<Person>().Where(a => a.Name!.Value == "Peter"))
                .FirstAsync();
            // there is already Marko --Knows--> Vadas, add circular reference back to Marko
            await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Vadas")
                .AddE<Knows>()
                .To(__ => __.V<Person>().Where(a => a.Name!.Value == "Marko"))
                .FirstAsync();

            var knownPersonsToMarko = await g
                .V<Person>()
                .Where(a => a.Name!.Value == "Marko")
                .Repeat(_ => _.Out<Knows>().OfType<Person>())
                .Emit()
                .SimplePath()
                .Dedup()
                .ToArrayAsync();

            await Output.WriteLineAsync($"Who does Marko know directly of indirectly?");

            foreach (var person in knownPersonsToMarko)
            {
                await Output.WriteLineAsync($"Marko knows {person.Name}.");
            }

            await Output.WriteLineAsync();
        }
```

**Comment by jiatao99** [comment]
Another question, is there anyway to dump the gremlin query as string on what's been send to server (cosmodb)?

**Comment by danielcweber** [comment]
This repo is about to be abandoned in favour of the new `dotnet new` templates. If questions persist, open a discussion in the main repo or schedule a support session (see main repo readme for details).
