### ISSUE TITLE
Upgrade samples to use version 9 of Gremlinq

### ISSUE THREAD

**Issue by ManfredLange** [ExRam/ExRam.Gremlinq.Samples#16]
Compiling the samples as they are with `#define JanusGraph` will result in compile errors.

The samples don't compile with Gremlinq version 9.

Compile errors include:
1. `CS0103: The name 'GraphModel' does not exist in the current context` which can be resolved by adding `using ExRam.Gremlinq.Core.Models;`
2. `CS1929: 'IGremlinQueryEnvironment' does not contain a definition for 'UseJanusGraph' and the best extension method overload 'ConfigurableGremlinQuerySourceExtensions.UseJanusGraph(IConfigurableGremlinQuerySource, Func<IJanusGraphConfigurator, IGremlinQuerySourceTransformation>)' requires a receiver of type 'IConfigurableGremlinQuerySource'`

Unfortunately, there doesn't appear any documentation as to how to resolve the breaking change. One option certainly would be to dig into the commit history. Another option would be to look at the automated tests. The latter use an unusual format so do not provide an accessible way to find an example for how to change it.

For now I'll stay on version 8.6.0.

**Comment by danielcweber** [comment]
That's just a missing closing parenthesis for ConfigureEnvironment.

**Comment by ManfredLange** [comment]
@danielcweber Thank you, Daniel!
