### ISSUE TITLE
Add Example to find edge between two vertices

### ISSUE THREAD

**Issue by jijothomas27** [ExRam/ExRam.Gremlinq.Samples#17]
Could you please add an example that finds the edges between two vertices?

**Comment by snap608** [comment]
Ok.. Now after a while and learning a lot more here is my solution...
(Person -> Follow -> Person scenario)

Get edges of a type:
```csharp
_g.V<Person>(sourcePerson.Id)
  .OutE<Follow>()
  .As((__, edge) => __
      .InV<Person>()
      .Where(u => u.Id == targetPerson.Id)
      .Select(edge)
  )
  .ToArrayAsync()
```

Get all edges from source to target:
```csharp
_g.V<Person>(sourcePerson.Id)
  .OutE()
  .As((__, edge) => __
      .InV<Person>()
      .Where(u => u.Id == targetPerson.Id)
      .Select(edge)
  )
  .ToArrayAsync()
```

Get all edges both directions:
```csharp
_g.V<Person>(sourcePerson.Id)
  .BothE()
  .As((__, edge) => __
      .InV<Person>()
      .Where(u => u.Id == targetPerson.Id)
      .Select(edge)
  )
  .ToArrayAsync()
```

**Comment by NiHe187** [comment]
@snap608 thank you for your solution, it really helped me 👍 

But I think the 
> Get all edges both directions:

 solution should have `OtherV` instead of `InV`.
Just like this:
```
_g.V<Person>(sourcePerson.Id)
  .BothE()
  .As((__, edge) => __
      .OtherV<Person>()
      .Where(u => u.Id == targetPerson.Id)
      .Select(edge)
  )
  .ToArrayAsync()

**Comment by danielcweber** [comment]
This repo is about to be abandoned in favour of the new `dotnet new` templates. If questions persist, open a discussion in the main repo or schedule a support session (see main repo readme for details).
