### ISSUE TITLE
"env" is not available when uncommenting 

### ISSUE THREAD

**Issue by martinoss** [ExRam/ExRam.Gremlinq.Samples#18]
https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/811c77fa3e8139c4563a3b0447da303ad291f36f/ExRam.Gremlinq.Samples.Console/Program.cs#L61

**Comment by danielcweber** [comment]
Right. There've been some changes and this commented line somehow got through. You'll have to use an ILogger instance that you created upfront, e.g. by creating a logger instance like [here](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/811c77fa3e8139c4563a3b0447da303ad291f36f/ExRam.Gremlinq.Samples.Console/Program.cs#L25). There's currently no other way.

**Comment by himadrinath** [comment]
@martinoss @danielcweber did anyone find any solution

ExRam.Gremlinq.Providers.CosmosDb.AspNet 11.0.0
Gremlin.Net 3.6.1

unable to config this

[ConfigureGremlinClient](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/811c77fa3e8139c4563a3b0447da303ad291f36f/ExRam.Gremlinq.Samples.Console/Program.cs#L56)
 not present

and [env](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/811c77fa3e8139c4563a3b0447da303ad291f36f/ExRam.Gremlinq.Samples.Console/Program.cs#L61) is outside of the scope
