### ISSUE TITLE
Could not load type 'ExRam.Gremlinq.Core.GraphElements.IVertex

### ISSUE THREAD

**Issue by pedrohma** [ExRam/ExRam.Gremlinq.Samples#19]
After initializing the gremlinQuerySource i'm getting the following exception:

System.TypeLoadException: 'Could not load type 'ExRam.Gremlinq.Core.GraphElements.IVertex' from assembly 'ExRam.Gremlinq.Core, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.'

![image](https://user-images.githubusercontent.com/6583751/183524004-b3b3d6f2-f5aa-411c-b166-0afb30142cfb.png)

This error is happening after migrating from .net core 3.1 to 6. I already updated the Gremlinq packages to v10 (as shown in the samples).

![image](https://user-images.githubusercontent.com/6583751/183524180-36053458-df2b-40e3-979b-6cc788d08986.png)

Any ideas?

**Comment by danielcweber** [comment]
This must have slipped through. It looks a lot like a version mismatch somewhere, where you reference different versions of various packages. From your screenshot, it's already apparent that there is no need to reference ...WebSocket and ...Core when there is a reference to ...CosmosDb.
