### ISSUE TITLE
How can I write direct groovy to query my db?

### ISSUE THREAD

**Issue by robertmrobo** [ExRam/ExRam.Gremlinq.Samples#2]
I have a method in my repository class which accepts two parameters (a property name and its value) and then queries the database for all vertices with the properties that matches the value.

I could achieve querying the db with a where clause in other methods, like this.
`            var personsOlderThan30 = await _g
                .V<Person>()
                .Where(x => x.Age > 30);`

But for this particular generic method there's a strong need of implementing a method which takes the parameter name and its value.

If there's no way I can do it in Gremlinq, i think going under the cover and do something like

`public async Task<T> GetByPropertyAsync (string prop, string value)
{
return g.V().has('prop','value')`
}

**Comment by danielcweber** [comment]
You might want to check out [Gremlin.net](https://www.nuget.org/packages/Gremlin.Net/). It's more low level than ExRam.Gremlinq and allows you to query databases with plain groovy.

**Comment by robertmrobo** [comment]
> You might want to check out [Gremlin.net](https://www.nuget.org/packages/Gremlin.Net/). It's more low level than ExRam.Gremlinq and allows you to query databases with plain groovy.

Ok, I know about Gremlin.net and just moved away of it in favour of Gremlinq for obvious reasons. :). I just thought  maybe there was a way to do plain groovy in Gremlinq.

Sure that's what Im gonna do. thanks...

**Comment by danielcweber** [comment]
That's the whole point of Gremlinq: To reach a higher level of abstraction. You may easily use both tools side by side. In fact, since Gremlinq depends on Gremlin.Net, you have Gremlin.Net already included in your project.
