### ISSUE TITLE
Add example for .ConfigureExecutor() and .UseExecutor()

### ISSUE THREAD

**Issue by menth0l** [ExRam/ExRam.Gremlinq.Samples#5]
Can You provide some examples on how to implement custom query executor logic?  In on of the issues It's been suggested that this is the way to log used RU/s returned in headers by Cosmos DB but no example has been provided.

**Comment by danielcweber** [comment]
This repo is about to be abandoned in favour of the new `dotnet new` templates. If questions persist, open a discussion in the main repo or schedule a support session (see main repo readme for details).
