### ISSUE TITLE
Bitwise operators example

### ISSUE THREAD

**Issue by menth0l** [ExRam/ExRam.Gremlinq.Samples#7]
Can You provide an example how to use bitwise operators in filters? 

My sample graph consist of documents and users which have different permission types for these documents. 

`document >--- IsAccessibleBy ---> user`

`IsAccessibleBy` is an edge with `Permissions` property:

`public class IsAccessibleBy : Edge 
    {
        public PermissionType Permissions { get; set; }
    }`

PermissionType is just an enum:
`
[Flags]
public enum PermissionType 
{
	Read = 1,
	Write = 2
}`

Now, let's say i want to get all edges with `Read` access level. I've tried this approach:

`g.V<Document>(id)
    .OutE<IsAccessibleBy>()
    .Where(_ => (_.Permissions & PermissionType.Read) > 0)`

but it fails with error:

`variable '_' of type 'SampleProject.PermissionTypeEdge' referenced from scope '', but it is not defined`

Any suggestions?

**Comment by danielcweber** [comment]
The question for this kind of issues is always: What would it look like in pure Gremlin? If there's an equivalent way to express this in pure Gremlin, then it might be possible (at least in the future) to express this in ExRam.Gremlinq. But is there? I am not aware of the ability to deal with bitwise operators in Gremlin.
