### ISSUE TITLE
Suggestion: Include an example that returns edge properties

### ISSUE THREAD

**Issue by neildonkin** [ExRam/ExRam.Gremlinq.Samples#9]
Thanks for creating this library.  It looks really useful, but there is one scenario I believe is missing from the sample code.  This is more of a suggestion than an issue, but it would be great if the sample code showed how to include edge properties in a query.

For example, if I add a `Since` property to the `Knows` edge to show how long each person has known each other:

```
public class Knows : Edge
{
     public DateTime Since { get; set; }
}
```

How could this value be retrieved and output in the `Who_does_Marko_know` method?  Is it even possible to do this?

**Comment by danielcweber** [comment]
One way would be use projection (like [here](SimpleVertexProperty )] to project an edge to its property value and its in-vertex (InV). PRs accepted!

**Comment by neildonkin** [comment]
Thanks, but the link does not work,

**Comment by danielcweber** [comment]
Sorry. Edited. Thou shalt not copy paste two things at the same time ;-)

**Comment by neildonkin** [comment]
I've created a PR https://github.com/ExRam/ExRam.Gremlinq.Samples/pull/12 showing how to do this.
